export const FETCH_ALLBREEDS_REQUEST = "FETCH_ALLBREEDS_REQUEST";
export const FETCH_ALLBREEDS_SUCCESS = "FETCH_ALLBREEDS_SUCCESS";
export const FETCH_ALLBREEDS_FAILURE = "FETCH_ALLBREEDS_FAILURE";

export const FETCH_RANDOMBREED_REQUEST = "FETCH_RANDOMBREED_REQUEST";
export const FETCH_RANDOMBREED_SUCCESS = "FETCH_RANDOMBRRED_SUCCESS";
export const FETCH_RANDOMBREED_FAILURE = "FETCH_RANDOMBREED_FAILURE";

export const FETCH_ALLBREEDNAMES_REQUEST = "FETCH_ALLBREEDNAMES_REQUEST";
export const FETCH_ALLBREEDNAMES_SUCCESS = "FETCH_ALLBREEDNAMES_SUCCESS";
export const FETCH_ALLBREEDNAMES_FAILURE = "FETCH_ALLBREEDNAMES_FAILURE";
